MODULE = gnrc_6tisch

DIRS += 02a-MAClow
DIRS += 02b-MAChigh
DIRS += cross-layers

export INCLUDES += -I$(CURDIR)/02a-MAClow -I$(CURDIR)/02b-MAChigh -I$(CURDIR)/include -I$(CURDIR)/cross-layers

include $(RIOTBASE)/Makefile.base
